"""add data col

Revision ID: 05ef3d455804
Revises: 94f7d91d005d
Create Date: 2026-02-03 18:26:40.245236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ef3d455804'
down_revision: Union[str, Sequence[str], None] = '94f7d91d005d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_segments', sa.Column('s3_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_segments', 's3_key')
    # ### end Alembic commands ###
