"""add data column to

Revision ID: 0ce5fbf04b6c
Revises: 05ef3d455804
Create Date: 2026-02-03 20:07:48.457240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce5fbf04b6c'
down_revision: Union[str, Sequence[str], None] = '05ef3d455804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_segments_transcription_tsv'), table_name='report_segments', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_report_segments_transcription_tsv'), 'report_segments', [sa.literal_column("to_tsvector('russian'::regconfig, transcription::text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
