"""initial schema

Revision ID: 80a7e5919279
Revises: 
Create Date: 2026-02-13 02:20:30.092013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a7e5919279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_json_s3_key', sa.String(), nullable=True),
    sa.Column('result_docx_s3_key', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_operations_operation_id'), 'pipeline_operations', ['operation_id'], unique=True)
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline_operations.operation_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pipeline_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('start', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('end', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('id_speaker', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=False),
    sa.Column('transcription', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['pipeline_operations.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_segments_operation_id'), 'pipeline_segments', ['operation_id'], unique=False)
    op.create_table('pipeline_temp_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operation_id'], ['pipeline_operations.operation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_temp_data_operation_id'), 'pipeline_temp_data', ['operation_id'], unique=False)
    op.create_table('meeting_microphones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('mic_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'mic_number', name='unique_mic_per_meeting')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_microphones')
    op.drop_index(op.f('ix_pipeline_temp_data_operation_id'), table_name='pipeline_temp_data')
    op.drop_table('pipeline_temp_data')
    op.drop_index(op.f('ix_pipeline_segments_operation_id'), table_name='pipeline_segments')
    op.drop_table('pipeline_segments')
    op.drop_table('meetings')
    op.drop_index(op.f('ix_pipeline_operations_operation_id'), table_name='pipeline_operations')
    op.drop_table('pipeline_operations')
    # ### end Alembic commands ###
