"""add data column

Revision ID: 94f7d91d005d
Revises: 80347198a7f0
Create Date: 2026-02-02 13:42:28.037411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f7d91d005d'
down_revision: Union[str, Sequence[str], None] = '80347198a7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('id_speaker', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=100), nullable=False),
    sa.Column('start', sa.Float(), nullable=False),
    sa.Column('end', sa.Float(), nullable=False),
    sa.Column('transcription', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_segments_report_id'), 'report_segments', ['report_id'], unique=False)
    op.create_index('ix_report_segments_report_time', 'report_segments', ['report_id', 'start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_segments_report_time', table_name='report_segments')
    op.drop_index(op.f('ix_report_segments_report_id'), table_name='report_segments')
    op.drop_table('report_segments')
    # ### end Alembic commands ###
